liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        place_teaser:
            quality: 75
            filters:
                thumbnail: { size: [300, 300], mode: outbound }