# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin.place:
        class: AppBundle\Admin\PlaceAdmin
        arguments: [~, AppBundle\Entity\Place, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Place }
    admin.image:
        class: AppBundle\Admin\ImageAdmin
        arguments: [~, AppBundle\Entity\Image, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Image }

    app.provider.oauth:
        class: AppBundle\Security\OAuthUserProvider
        arguments: ['@fos_user.user_manager',{facebook: facebook_id, google: google_id}]